hbw/app/models/hbw/fields/select.rb, hbw/lib/hbw/engine.rb, hbw/lib/hbw/logger.rb, spec/hbw/fields/select_spec.rb
* Fix setting lookup value
* Refactoring and logging for retrieving options by source
=> HOMS-117 Fix lookup

README.md, config/imprint.yml.sample, docker-compose.yml
* sync imprint.yml.sample with imprint.default.yml;
* add common network;
* add volume for config.
=> HPF-18 Changes for running HOMS in docker ecosystem

config/locales/en.yml, lib/imprint/services/order_printing_service.rb, spec/features/orders/list_orders_spec.rb
Fix https://github.com/latera/homs/issues/79
=> HOMS-163 Fix filtering orders when filter by user name is not set

Dockerfile, docker-compose.yml, wait_for_postgres.sh
ref https://github.com/latera/activiti-homs-docker/pull/2
=> HOMS-164 Add postgresql-client for check DB availability

app/controllers/api/base_controller.rb, app/controllers/orders_controller.rb, app/views/orders/_filter_by.html.haml, config/application.rb, hbw/app/controllers/hbw/tasks_controller.rb, hbw/config/yml_api.test.yml, spec/hbw/features/bp_form_submit_spec.rb, spec/rails_helper.rb
* Fix BP form submit + test
* Set UTC±00 timezone for tests
=> HOMS-207 Permit all parameters by default

Dockerfile
Do I have to add something to bamboo?
=> HOMS-215 Add VERSION file

Gemfile, Gemfile.lock, config/bpm.yml.sample, config/hbw.yml.sample, docker-compose.dev.oracle.yml
* Use ruby-oci8 with https://github.com/kubo/ruby-oci8/pull/144 fix
* Improve sample configs a little
=> HBW-71 Update ruby-oci8

README.md
Cleaning up development installation instruction
=> HOMS-220 Improve README

CHANGELOG.md, app/javascript/packs/hbw.js, config/webpack/loaders/babel.js, docker-compose.test.yml, hbw/app/javascript/packs/hbw/components/form.js.jsx, hbw/app/javascript/packs/hbw/components/form/select.js.jsx, hbw/app/javascript/packs/hbw/components/form/user.js.jsx, hbw/app/models/hbw/fields/user.rb, hbw/config/locales/en.yml, hbw/config/locales/ru.yml, hbw/config/yml_oracle.default.yml, package.json, spec/hbw/features/select_spec.rb, spec/hbw/features/show_bp_form_spec.rb, spec/hbw/features/user_spec.rb, spec/support/helpers/orders_helper.rb, yarn.lock
=> HBW-79 Replace Select2 with react-select in widget

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/form/select_table.js.jsx
=> HBW-126 Change colors on select and hover of select_table

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/form/file_upload.js.jsx, hbw/config/locales/en.yml, hbw/config/locales/ru.yml
=> HBW-129 Add drag and drop field for file upload

hbw/config/locales/ru.yml
=> HOMS-284 Change loading bp translation

Dockerfile, Dockerfile.oracle
Turned off `CHANGELOG.md` checker.
=> INT-63 Add curl and telnet to Dockerfile

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/priority.jsx, hbw/app/javascript/packs/hbw/components/claiming/table.jsx, hbw/app/javascript/packs/hbw/components/claiming/task_overview.jsx, hbw/app/javascript/packs/hbw/init/date_localizer.js, hbw/app/javascript/packs/hbw/widget.js.jsx, hbw/config/locales/en.yml, package.json, yarn.lock
=> HBW-169 Add task overview component

hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/shared/created_date.jsx, hbw/app/javascript/packs/hbw/components/claiming/shared/due_date.jsx, hbw/app/javascript/packs/hbw/components/claiming/shared/task_list_context.jsx, hbw/app/javascript/packs/hbw/components/claiming/shared/task_tabs.jsx, hbw/app/javascript/packs/hbw/components/claiming/table.jsx, hbw/app/javascript/packs/hbw/components/claiming/task_list.jsx, hbw/app/javascript/packs/hbw/components/claiming/task_overview.jsx, hbw/config/locales/en.yml
=> HBW-182 Wrap task list page together

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/pop_up.jsx, hbw/app/javascript/packs/hbw/components/claiming/shared/task_list_context.jsx, hbw/app/javascript/packs/hbw/components/claiming/short_list.jsx, spec/hbw/features/tasks/task_counter_spec.rb
=> HBW-206 Add description to popup task list

hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/shared/due_date.jsx, hbw/app/javascript/packs/hbw/components/claiming/table.jsx, hbw/config/locales/en.yml, spec/hbw/features/tasks/search_spec.rb, spec/hbw/features/tasks/task_counter_spec.rb, spec/hbw/features/tasks/task_list_spec.rb, spec/javascript/due_date.test.jsx
Also fixed submit_select margin, now it works correct for all button types
=> HBW-207 Fix tasks table

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/assets/stylesheets/hbw/variables.sass, hbw/app/javascript/packs/hbw/components/claiming/short_list.jsx, hbw/app/javascript/packs/hbw/components/claiming/table.jsx, hbw/app/javascript/packs/hbw/components/claiming/task_overview.jsx, spec/hbw/features/tasks/task_list_spec.rb
=> HBW-212 Adjust new elements with existent style

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/menu_button.jsx, hbw/app/javascript/packs/hbw/components/claiming/notifier.js, hbw/config/locales/en.yml, hbw/config/yml_api.test.camunda.yml
=> HBW-211 Notify user about new assigned tasks

hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/notifier.js, hbw/config/locales/en.yml
=> HBW-221 Change notification text

.env.sample, CHANGELOG.md, Gemfile, Gemfile.lock, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, config/cable.yml.sample, docker-compose.yml
=> HBW-243 Add ActionCable to HBW

CHANGELOG.md, hbw/app/controllers/hbw/tasks_controller.rb, hbw/app/javascript/packs/hbw/components/shared/context/store.jsx, hbw/app/models/hbw/common/adapter.rb, hbw/app/models/hbw/task.rb, hbw/app/models/hbw/widget.rb, hbw/app/views/hbw/tasks/list.json.jbuilder, hbw/config/routes.rb, hbw/config/yml_api.test.camunda.yml
App is not using this store for now, just initializing it, because there is no way to use it before https://dev.latera.ru/browse/HBW-255 without breaking a bunch of tests. New store will be used in the mentioned issue.
=> HBW-250 Initialize store context with full task list

hbw/app/javascript/packs/hbw/components/claiming/task_list.jsx, hbw/app/javascript/packs/hbw/components/form.js.jsx, hbw/app/javascript/packs/hbw/components/shared/context/store.jsx, hbw/config/yml_api.test.camunda.yml
=> HBW-256 Forced update task data in case of claim

.eslintrc, CHANGELOG.md, hbw/app/controllers/hbw/tasks_controller.rb, hbw/app/javascript/packs/hbw/components/container.js.jsx, hbw/app/javascript/packs/hbw/components/entity_task.js.jsx, hbw/app/javascript/packs/hbw/components/shared/context/store.jsx, hbw/app/models/hbw/common/adapter.rb, hbw/app/models/hbw/widget.rb, hbw/app/views/hbw/tasks/_form.json.jbuilder, hbw/app/views/hbw/tasks/_task.json.jbuilder, hbw/app/views/hbw/tasks/forms.json.jbuilder, hbw/config/routes.rb
=> HBW-270 Get tasks by entities lazy

CHANGELOG.md, app/javascript/packs/application.js, app/javascript/utils/messenger.js, config/webpack/shared.js, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/claiming/task_list.jsx, hbw/app/javascript/packs/hbw/components/shared/context/store.jsx
Service Provider Console integration example:
=> HOMS-302 Turn Messenger class to importable module

README.md
I guess there's no need to update changelog
=> HOMS-335 Added a couple of useful links

.rubocop_todo.yml, CHANGELOG.md, app/controllers/imprint/prints_controller.rb, app/models/imprint/api.rb, lib/imprint/services/order_printing_service.rb
=> HOMS-349 Handle connection error when try to print order

Dockerfile.test, spec/features/orders/edit_order_spec.rb, spec/features/orders/print_order_spec.rb, spec/support/capybara.rb
It's stable green now (>10 builds in a row). Probably because of new chrome/chromedriver.
=> HOMS-288 Fix tests with fontawesome icons

README.md, WITHOUT_ORACLE.md, WITH_ORACLE.md, hbw/app/javascript/packs/hbw/widget.js.jsx
https://user-images.githubusercontent.com/36504360/109015374-1c941100-76c6-11eb-9239-8709af7f6cb3.mp4
=> HOMS-360 Call fetchBPTranslations in renders widget functions

CHANGELOG.md, hbw/app/assets/stylesheets/hbw.sass, hbw/app/assets/stylesheets/hbw/brand_variables.sass, hbw/app/assets/stylesheets/hbw/branding.sass, hbw/app/javascript/packs/hbw/components/form/select.js.jsx, hbw/app/javascript/packs/hbw/components/form/string.js.jsx, hbw/config/yml_api.test.camunda.yml, spec/hbw/features/bp_form/description_string_spec.rb, spec/hbw/features/tasks/search_spec.rb, spec/hbw/features/tasks/task_counter_spec.rb, spec/hbw/features/tasks/task_list_spec.rb
```
form:
css_class: col-xs-12 col-sm-6 col-md-5 col-lg-4
fields:
- name: topDescriptionString
type: string
label: String label 1
description:
placement: top
text: Top description test
placeholder: Test placeholder
css_class: col-xs-6 col-sm-4 col-md-3
- name: bottomDescriptionString
type: string
label: String label 2
description:
placement: bottom
text: Bottom description test
css_class: col-xs-6 col-sm-4 col-md-3
```
=> HBW-318 Add top/bottom descriptions and placeholder for string component

CHANGELOG.md, hbw/app/assets/stylesheets/hbw/brand_variables.sass, hbw/app/assets/stylesheets/hbw/branding.sass, hbw/app/javascript/packs/hbw/components/form/select.js.jsx, hbw/app/javascript/packs/hbw/components/form/string.js.jsx, hbw/app/models/hbw/fields/select.rb, hbw/config/yml_api.test.camunda.yml, spec/hbw/features/select_spec.rb
=> HBW-320 Add custom description for select component

CHANGELOG.md, hbw/app/assets/stylesheets/hbw/brand_variables.sass, hbw/app/assets/stylesheets/hbw/branding.sass, hbw/app/javascript/packs/hbw/components/form/file_upload.js.jsx
=> HBW-351 Add customization capability for file_upload

CHANGELOG.md, README.md, hbw/app/javascript/packs/hbw/components/form/file_upload.js.jsx, hbw/config/yml_api.test.camunda.yml, spec/hbw/features/file_upload_spec.rb
Try to add several files through button "browse" without "multiple" prop and with this one (try to select several filest through shift + click):
Try to add several files through drug&drop without "multiple" prop and with this one:
=> HBW-344 Append files to form instead of substituting when multiple prop is set up

hbw/app/assets/stylesheets/hbw/brand_variables.sass, hbw/app/assets/stylesheets/hbw/branding.sass, hbw/app/javascript/packs/hbw/components/form/file_upload.js.jsx
=> HBW-351 Add browse link text customization capability

CHANGELOG.md, hbw/app/javascript/packs/hbw/components/entity_tasks.js.jsx, spec/hbw/features/bp_form/translation_spec.rb
HBW-359 Translate BP name with correct translator
<details>
<summary>Screens</summary>
</details>
=> HBW-359 Translate BP name with correct translator

CHANGELOG.md, app/controllers/application_controller.rb, app/javascript/utils/messenger.js, config/locales/devise.ru.yml, spec/features/users/sign_in_spec.rb
HOMS-297 Show message about incorrect sign in
<details>
<summary>Screen of message</summary>
</details>
<details>
<summary>Message that appears when unauthorized login to main page</summary>
</details>
=> HOMS-297 Show message about incorrect sign in

CHANGELOG.md, hbw/app/javascript/packs/hbw/components/form/select_table.js.jsx, hbw/config/yml_api.test.camunda.yml, spec/hbw/features/bp_form/dynamic_conditions_by_select_table_spec.rb, spec/hbw/features/tasks/search_spec.rb, spec/hbw/features/tasks/task_counter_spec.rb, spec/hbw/features/tasks/task_list_spec.rb
=> HBW-331 Dynamic delete_if and disable_if options for select_table

CHANGELOG.md, hbw/app/javascript/packs/hbw/components/form/select_table.js.jsx, hbw/app/javascript/packs/hbw/components/shared/hoc/select.js, hbw/config/yml_api.test.camunda.yml, spec/hbw/features/bp_form/validation_spec.rb, spec/hbw/features/select_table_spec.rb, spec/support/helpers/tables_helper.rb
* Initialisation of rows
* Allowed table states
=> HBW-364 Fix select table in edge cases

.eslintrc, CHANGELOG.md, app/javascript/utils/messenger.js, docker-compose.dev.yml, docker-compose.oracle.yml, docker-compose.yml, hbw/app/assets/stylesheets/hbw.sass, hbw/app/controllers/hbw/api_controller.rb, hbw/app/controllers/hbw/buttons_controller.rb, hbw/app/controllers/hbw/tasks_controller.rb, hbw/app/controllers/hbw/users_controller.rb, hbw/app/javascript/packs/hbw/components/app.jsx, hbw/app/javascript/packs/hbw/components/buttons.js.jsx, hbw/app/javascript/packs/hbw/components/container.js.jsx, hbw/app/javascript/packs/hbw/components/error.tsx, hbw/app/javascript/packs/hbw/components/form.js.jsx, hbw/app/javascript/packs/hbw/components/form/file_upload.js.jsx, hbw/app/javascript/packs/hbw/components/shared/context/error_handling.tsx, hbw/app/javascript/packs/hbw/components/shared/context/store.jsx, hbw/app/javascript/packs/hbw/components/shared/utils/errors.tsx, hbw/app/javascript/packs/hbw/widget.js.jsx, hbw/app/models/hbw/remote.rb, hbw/config/locales/en.yml, hbw/config/locales/ru.yml, spec/features/order_types/new_order_type_spec.rb
=> HOMS-339 Add the output of errors for the availability of the Сamunda service to the widget

spec/features/order_types/new_order_type_mock.yml, spec/features/order_types/new_order_type_spec.rb, spec/features/orders/edit_order_spec.rb, spec/features/orders/list_orders_spec.rb, spec/features/orders/new_order_spec.rb, spec/features/orders/orders_mock.yml, spec/features/orders/print_order_spec.rb, spec/features/users/sign_in_spec.rb, spec/features/users/sign_out_spec.rb, spec/features/users/user_index_spec.rb, spec/features/users/user_show_spec.rb, spec/features/users/users_mock.yml, spec/features/users/users_spec.rb
=> HOMS-376 Localise leftover camunda api mock files in tests spec/features

CHANGELOG.md, app/assets/stylesheets/framework_and_overrides.sass, app/javascript/init/unwrap_moment.js, app/javascript/packs/application.js, hbw/app/assets/stylesheets/hbw.sass, hbw/app/assets/stylesheets/hbw/branding.sass, hbw/app/javascript/packs/hbw/components/form/datetime.js.jsx, hbw/app/javascript/packs/hbw/components/shared/element/date_picker_wrapper.jsx, hbw/app/javascript/packs/hbw/components/shared/utils/to_fns_date_format.js, hbw/app/javascript/packs/hbw/init/date_localizer.js, hbw/app/javascript/packs/hbw/init/dependencies.js, hbw/app/javascript/packs/hbw/init/noconflict.js, hbw/app/javascript/packs/hbw/init/wrap_globals.js, package.json, spec/hbw/features/bp_form/description_date_time_spec.rb, spec/hbw/features/bp_form/disabled_fields_spec.rb, spec/hbw/features/bp_form/dynamic_conditions_by_checkbox_spec.rb, spec/hbw/features/bp_form/dynamic_conditions_by_datetime_mock.yml, spec/hbw/features/bp_form/dynamic_conditions_by_datetime_spec.rb, spec/hbw/features/bp_form/dynamic_conditions_by_radio_button_spec.rb, spec/hbw/features/bp_form/dynamic_conditions_by_select_spec.rb, spec/hbw/features/bp_form/dynamic_conditions_by_select_table_spec.rb, spec/hbw/features/bp_form/dynamic_conditions_by_string_spec.rb, spec/support/helpers/fill_helper.rb, spec/support/helpers/orders_helper.rb, yarn.lock
* Deleted moment.js and bootstrap-datetimepicker dependencies from widget
* Added react-datepicker dependency
* Remade HBWFormatDatetime component with react-datepicker
* Added converFormat function to conver moment.js date format to dat-fns format style
* Adjusted stylesheets
* Fixed tests
Before:
After:
=> HBW-267 Replace bootstrap-datetimepicker with react-datepicker

CHANGELOG.md, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.haml, config/locales/en.yml, spec/features/users/delete_user_spec.rb, spec/models/user_spec.rb
=> HOMS-384 Add deleting users

hbw/app/models/hbw/camunda/adapter.rb, yarn.lock
other deps will be in HOMS-387
=> HOMS-388 Update deps

CHANGELOG.md, hbw/app/javascript/packs/hbw/widget.js.jsx
Fixed typo in variable to display notifications
=> HBW-363 Fix typo in variable to display notifications

CHANGELOG.md
=> Fix CHANGELOG after release

CHANGELOG.md, app/views/devise/sessions/new.html.erb, config/homs_configuration.yml.sample, config/locales/en.yml, config/locales/ru.yml
<details>
<summary>Screen</summary>
</details>
=> HOMS-394 Make a login form with SSO

.env.sample, .env.test, CHANGELOG.md, config/hbw.yml.sample
FIxes https://github.com/latera/homs/issues/605
=> Make Minio host configurable through env variable

README.md
=> HOMS-398 Add SSO part to README

CHANGELOG.md, app/models/user.rb, app/views/users/_form_fields.html.haml, app/views/users/edit.html.haml, app/views/users/new.html.haml, db/migrate/20220512040821_add_directory_to_user.rb, db/schema.rb
=> HOMS-415 Differentiate users from Keycloak and regular

CHANGELOG.md, Gemfile.lock, README.md, app/controllers/concerns/keycloak_utils.rb, app/views/devise/sessions/new.html.erb, config/homs_configuration.default.yml, config/homs_configuration.yml.sample, lib/container.rb
refs https://github.com/hydra-billing/hydra-keycloak-client/pull/22
=> HOMS-435 Downcase key in the config & treat redis port as a number

README.md, app/controllers/concerns/keycloak_utils.rb, app/models/user.rb
refs https://github.com/hydra-billing/hydra-keycloak-client/pull/26
=> HOPER-5490 Use native Keycloak fields instead of user attributes

config/bpm.yml.sample, config/homs_configuration.default.yml, config/homs_configuration.yml.sample
fixes https://github.com/hydra-billing/homs/issues/679
=> Keep SSO disabled by default

hbw/app/assets/stylesheets/hbw/brand_variables.sass, hbw/app/assets/stylesheets/hbw/branding.sass
Regular error:
* before
* after
Error tooltip:
* before
* after
=> HOMS-466 Make red error color dimmer

CHANGELOG.md, config/environments/development.rb, config/locales/bp/en.new_business_process.yml, hbw/app/assets/stylesheets/hbw.sass, hbw/app/javascript/packs/hbw/components/form.js.jsx, hbw/app/javascript/packs/hbw/components/form/services_table/modal_wrapper.tsx, hbw/app/javascript/packs/hbw/components/form/services_table/service_add_modal.tsx, hbw/app/javascript/packs/hbw/components/form/services_table/services_table.tsx, hbw/app/javascript/packs/hbw/components/form/services_table/table_footer.tsx, hbw/app/javascript/packs/hbw/components/form/services_table/table_title.tsx, hbw/app/models/hbw/fields/services_table.rb, hbw/config/locales/en.yml, hbw/config/yml_oracle.default.yml, spec/hbw/features/bp_form/services_select_mock.yml, spec/hbw/features/bp_form/services_select_spec.rb
https://github.com/hydra-billing/homs/assets/51130595/6502d011-fc39-4c04-be13-65eaab6bf730
=> HBW-402 Add parent service add modal

CHANGELOG.md, config/environments/development.rb, hbw/app/services/hbw/with_definitions.rb
https://github.com/hydra-billing/homs/assets/73141980/df4774e6-aefd-45fe-a129-a85f400b7288
=> HBW-409 Stop caching filtered process definition
